export const images = {
  common: {
    avatar: require('./images/avatar.png'),
  },
  illustration: {
    headerLeft: require('./images/header-illus-left.png'),
    headerRight: require('./images/header-illus-right.png'),
  },
  restaurants: {
    McDonal: require('./images/McDonal.png'),
  },
  food: {
    babySpinach: require('./images/baby-spinach.png'),
    chickenHawaii: require('./images/chicken-hawaiian.png'),
    default: require('./images/default-food.png'),
    masroom: require('./images/masroom.png'),
    pepperJuliened: require('./images/pepper-juliened.png'),
  },
};

export const icons = {
  asian: require('./icons/asian.png'),
  bell: require('./icons/bell.png'),
  bellGray: require('./icons/bell-gray.png'),
  browsing: require('./icons/browsing.png'),
  browsingGray: require('./icons/browsing-gray.png'),
  burger: require('./icons/burger.png'),
  cart: require('./icons/cart.png'),
  cartGray: require('./icons/cart-gray.png'),
  checkGray: require('./icons/check-gray.png'),
  chevronDownGray: require('./icons/chevron-down-gray.png'),
  chevronLeftBlack: require('./icons/chevron-left-black.png'),
  chevronRight: require('./icons/chevron-right.png'),
  clock: require('./icons/clock.png'),
  deliverMoto: require('./icons/deliver-moto.png'),
  donat: require('./icons/donat.png'),
  facebook: require('./icons/facebook.png'),
  google: require('./icons/google.png'),
  heart: require('./icons/heart.png'),
  heartGray: require('./icons/heart-gray.png'),
  menu: require('./icons/menu.png'),
  mexican: require('./icons/mexican.png'),
  minus: require('./icons/minus.png'),
  minusWhite: require('./icons/minus-white.png'),
  orders: require('./icons/orders.png'),
  ordersGray: require('./icons/orders-gray.png'),
  pizza: require('./icons/pizza.png'),
  plus: require('./icons/plus.png'),
  plusWhite: require('./icons/plus-white.png'),
  search: require('./icons/search.png'),
  switch: require('./icons/switch.png'),
};
