export const images = {
  common: {
    avatar: require('./images/avatar.png'),
  },
  icon: {
    menu: require('./images/menu-icon.png'),
    switch: require('./images/switch-icon.png'),
    search: require('./images/search-icon.png'),
    checkGray: require('./images/check-gray-icon.png'),
    deliverMoto: require('./images/deliver-moto-icon.png'),
    clock: require('./images/clock-icon.png'),
    burger: require('./images/burger-icon.png'),
    donat: require('./images/donat-icon.png'),
    pizza: require('./images/pizza-icon.png'),
    mexican: require('./images/mexican-icon.png'),
    asian: require('./images/asian-icon.png'),
    facebook: require('./images/facebook-icon.png'),
    google: require('./images/google-icon.png'),
    cart: require('./images/cart-icon.png'),
    cartGray: require('./images/cart-gray-icon.png'),
    browsing: require('./images/browsing-icon.png'),
    browsingGray: require('./images/browsing-gray-icon.png'),
    heart: require('./images/heart-icon.png'),
    heartGray: require('./images/heart-gray-icon.png'),
    bell: require('./images/bell-icon.png'),
    bellGray: require('./images/bell-gray-icon.png'),
    orders: require('./images/orders-icon.png'),
    ordersGray: require('./images/orders-gray-icon.png'),
    chevronLeftBlack: require('./icons/chevron-left-black.png'),
    chevronRight: require('./icons/chevron-right.png'),
    chevronDownGray: require('./icons/chevron-down-gray.png'),
    plus: require('./icons/plus-red.png'),
    plusWhite: require('./icons/plus-white.png'),
    minus: require('./icons/minus-red.png'),
    minusWhite: require('./icons/minus-white.png'),
  },
  illustration: {
    headerLeft: require('./images/header-illus-left.png'),
    headerRight: require('./images/header-illus-right.png'),
  },
  restaurants: {
    McDonal: require('./images/McDonal.png'),
  },
  food: {
    default: require('./images/default-food.png'),
    chickenHawaii: require('./images/chicken-hawaiian.png'),
    pepperJuliened: require('./images/pepper-juliened.png'),
    babySpinach: require('./images/baby-spinach.png'),
    masroom: require('./images/masroom.png'),
  },
};
